6. Nos últimos meses, foram feitas medições do tempo decorrido entre o início e
finalização de uma das etapas do processo de produção de certo produto. O tempo médio foi calculado em 26,5 minutos e o desvio padrão foi de 4,0 minutos. Sabendo que tal variável segue uma distribuição normal, identifique as seguintes informações:

> a) P(X>37)

> b) P(X<20)

> c) P(22<X<28)

In [ ]:
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
media = 26.5
desvio_padrao = 4

In [ ]:
valor_da_variavel = 37

In [ ]:
z = +(valor_da_variavel - media) / desvio_padrao

In [ ]:
z

2.625

A probabilidade P(Z>2.625) representa a probabilidade de obter um valor na distribuição normal padrão que está acima de 2.625 desvios padrão acima da média. Isso significa que você está calculando a probabilidade da cauda direita da distribuição normal padrão a partir de 2.625 desvios padrão acima da média.

In [ ]:
valor_da_variavel = 20

z = +(valor_da_variavel - media) / desvio_padrao

z

-1.625

a probabilidade P(Z<−1.625) representa a probabilidade de obter um valor na distribuição normal padrão que está abaixo de 1.625 desvios padrão abaixo da média. Isso significa que você está calculando a probabilidade da cauda esquerda da distribuição normal padrão a partir de 1.625 desvios padrão abaixo da média.

In [ ]:
# Probabilidade P(Z > 2.625)
probabilidade1 = 1 - norm.cdf(2.625)

# Probabilidade P(Z < -1.625)
probabilidade2 = norm.cdf(-1.625)

print(f'P(Z > 2.625): {probabilidade1:.4f}')
print(f'P(Z < -1.625): {probabilidade2:.4f}')

P(Z > 2.625): 0.0043
P(Z < -1.625): 0.0521


## Para calcular P(22<X<28), primeiro se calcula o Z valor de 22, depois o z valor de 28.

In [ ]:
valor_da_variavel = 22

z22 = +(valor_da_variavel - media) / desvio_padrao

z22

-1.125

In [ ]:
valor_da_variavel = 28

z28 = +(valor_da_variavel - media) / desvio_padrao

z28

0.375

In [ ]:
probabilidade22 = norm.cdf(z22)
probabilidade28 = norm.cdf(z28)

print(f'P(-1,125<Z<0,375)')
print(f'{probabilidade22:.4f}')
print(f'{probabilidade28:.4f}')

P(-1,125<Z<0,375)
0.1303
0.6462


Para calcular a probabilidade de o evento estar dentro do intervalo específico, soma-se as probabilidades.

Então, P(-1,125<Z<0,375) é 0.1303 + 0.6462, o que resulta em 0.7765, ou 77,65%.

In [ ]:
0.1303 + 0.6462

0.7765